---
- name: Download AWS Inspector agent installer.
  get_url:
    url: "{{ aws_inspector_url }}"
    dest: "{{ aws_inspector_installer_dest }}"

- name: Modify script to disable package manager signature check
  replace:
    path: "{{ aws_inspector_installer_dest }}"
    regexp: '^(\s+)(yum)( downgrade| install| reinstall)(.*)$'
    replace: '\1\2 --nogpgcheck\3\4'
  when: (awsagent_disable_gpgcheck) and (ansible_os_family == 'RedHat')

- name: Configure proxy if necessary
  template:
    src: awsagent.env.j2
    dest: /etc/init.d/awsagent.env
    owner: root
    group: root
    mode: '0644'
  notify: restart awsagent
  when: aws_inspector_proxy_enabled

- name: Ensure AWS Inspector agent is installed.
  command: bash "{{ aws_inspector_installer_dest }}"
  args:
    creates: "/etc/init.d/awsagent"
  when: not aws_inspector_role_test_mode

- name: Ensure awsagent service is running.
  service:
    name: awsagent
    state: "{{ awsagent_state }}"
    enabled: true
  when: not aws_inspector_role_test_mode
